[package]
name = "client_side_validation"
version = "0.8.2"
license = "Apache-2.0"
authors = ["Dr. Maxim Orlovsky <orlovsky@pandoracore.com>"]
description = "Client-side validation foundation library"
repository = "https://github.com/LNP-BP/client_side_validation"
homepage = "https://github.com/LNP-BP"
keywords = ["lnp-bp", "cryptocurrency", "smart-contracts", "blockchain"]
categories = ["cryptography::cryptocurrencies", "encoding", "parsing"]
readme = "README.md"
edition = "2021"
rust-version = "1.59.0"
exclude = [".github", "commit_verify", "strict_encoding", "single_use_seals"]

[lib]
name = "client_side_validation"
path = "src/lib.rs"

[dependencies]
strict_encoding = { version = "0.8.2", path = "./strict_encoding" }
commit_verify = { version = "0.8.2", path = "./commit_verify" }
single_use_seals = { version = "0.8.0", path = "./single_use_seals" }

[dev-dependencies]
async-trait = "0.1.51"

[features]
default = []
all = ["serde", "rand", "bitcoin", "crypto", "async", "bulletproofs", "float"]
async = ["single_use_seals/async"]
rand = ["commit_verify/rand"]
serde = ["commit_verify/serde"]
bitcoin = ["strict_encoding/bitcoin", "strict_encoding/miniscript"]
crypto = ["strict_encoding/crypto"]
bulletproofs = ["commit_verify/bulletproofs"]
float = ["strict_encoding/float"]

[package.metadata.docs.rs]
features = [ "all" ]

[workspace]
members = [".", "strict_encoding", "commit_verify", "single_use_seals",
           "strict_encoding/derive", "strict_encoding/derive_helpers", "strict_encoding/test_helpers"]
default-members = ["."]
