[package]
name = "commit_verify"
version = "0.8.3"
license = "Apache-2.0"
authors = ["Dr. Maxim Orlovsky <orlovsky@pandoracore.com>"]
description = "Commit-verify API for client-side validation"
repository = "https://github.com/LNP-BP/client_side_validation"
homepage = "https://github.com/LNP-BP"
keywords = ["lnp-bp", "cryptography", "smart-contracts", "commit-verify"]
categories = ["cryptography", "encoding"]
readme = "README.md"
edition = "2021"
rust-version = "1.59.0"

[lib]
name = "commit_verify"
path = "src/lib.rs"

[dependencies]
amplify = { version = "3.12.0", features = ["hex"] }
bitcoin_hashes = "0.10"
strict_encoding = { version = "0.8.0", path = "../strict_encoding" }
rand = { version = "0.8.4", optional = true }
serde_crate = { version = "1", package = "serde", optional = true }
serde_with = { version = "1.8", optional = true }
grin_secp256k1zkp = { version = "0.7", optional = true }

[dev-dependencies]
rand = "0.8.4"

[features]
default = []
all = ["rand", "serde", "bulletproofs"]
serde = ["serde_crate", "serde_with", "bitcoin_hashes/serde", "amplify/serde"]
bulletproofs = ["grin_secp256k1zkp"]

[package.metadata.docs.rs]
features = [ "all" ]
